version: "3"
services:
  ert-frontend:
    container_name: ert-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      WATCHPACK_POLLING: true
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - T-WEB

  ert-backend:
    container_name: ert-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/.:/app/.
    command: bash -c "npm install && npm start"
    networks:
      - T-WEB
    environment:
      ACCESS_SECRET: ${ACCESS_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}

  ert-mariadb:
    image: mariadb:latest
    container_name: ert-mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: EpicRoadTrip
    networks:
      - T-WEB

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - ert-mariadb
    ports:
      - "8081:8080"
    environment:
      PMA_HOST: ert-mariadb
    networks:
      - T-WEB

networks:
  T-WEB:
    name: T-WEB

volumes:
  mariadb:
