version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 8080
      #WATCHPACK_POLLING: true

    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src

  # mysql:
  #   image: mariadb:10.3
  #   container_name: mariadb
  #   volumes:
  #     - container-volume:/var/lib/mysql
  #     - ./SQL/EpicRoadTrip.sql:/docker-entrypoint-initdb.d/EpicRoadTrip.sql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: EpicRoadTrip
  #   ports:
  #     - "3306:3306"
